### ISSUE TITLE
Arrow Integration?

### ISSUE THREAD

**Issue by dr4ke616** [kittinunf/Forge#34]
Hey,

Was experimenting with this library, and its pretty great! I wonder could i make a suggestion? 

How do you feel about making use of [`Arrow`](https://github.com/arrow-kt/arrow) for various different data types? In doing so, this library can play much nicer with the wider Kotlin functional echosystem.

Some datatypes that may be super useful to your library:
- `Either<A, B>` over `com.github.kittinunf.result.Result`
- `Option<A>` for optionality
- `NonEmptyList<A>` to model non empty json arrays
- [`curry`](https://arrow-kt.io/docs/0.10/apidocs/arrow-core-data/arrow.core/kotlin.-function2/curry.html) which i noticed is used exensively as part of the library's API.

There may indeed be other tools Arrow has to offer that might benifit this library even further.  I understand that adding this may be a breaking change, but i noticed that the `1.0.0` version is still at alpha stage. So could be a good time to get it in before `1.0.0` is released.

**Comment by kittinunf** [comment]
@dr4ke616 Thanks for using/exploring the library, I really hope you like it.

Thanks again for the suggestion. But truth to be told, honestly I am reluctant to add any more dependencies into Fuse. Even though I really like and/or admire what the Arrow's team have done and achieve over there, I am not sure adding any more dependencies to this library is the right choice either.

Like Either and Curry, I think it would be extremely useful to this library but at the same time, because Fuse was designed to be simple, maybe too simple, but we actually don't need to bring 3rd part dep. into the lib if the functionality that Fuse uses could be replaced by just a single file.

Unless, I didn't see something too clearly, while it would be useful, but it looks like the price that we have to pay (by adding more things into Fuse) is something I really want to.
